name: Unit and Integration Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test MyWebApi.UnitTests --no-build --configuration Release

      - name: Run Integration Tests
        run: dotnet test MyWebApi.IntegrationTests --no-build --configuration Release
